name: Update APT Repo
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install -y dpkg-dev gnupg
    - name: Import GPG
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
    - name: Generate
      working-directory: docs
      env:
        GPG_ID: "8023F2155B2F4FCDF88418C46FD6ABC81CAFAEAC"
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      run: |
        ls -la pool/main/g/gerimo/
        dpkg-scanpackages pool/ /dev/null > Packages
        gzip -9 Packages
        apt-ftparchive release . > Release
        echo "$GPG_PASSPHRASE" | gpg --pinentry-mode loopback --passphrase-fd 0 --clearsign --local-user "$GPG_ID" -o InRelease Release
        gpg --detach-sign --local-user "$GPG_ID" -o Release.gpg Release
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update repo
